version: '3.10'
services:
  redis:
    image: redis:7
    container_name: app_redis
    env_file:
      - .env-non-dev


  app:
    build:
      context: .
    container_name: toDo_app
    env_file:
      - .env-non-dev
    command: ["/toDoList/docker/app.sh"]
    ports:
      - 9000:8000
    depends_on:
      - redis


  celery:
    build:
      context: .
    container_name: app_celery
    command: ["/toDoList/docker/celery.sh", "celery"]
    env_file:
      - .env-non-dev
    depends_on:
      - redis


  flower:
    build:
      context: .
    container_name: app_flower
    command: ["/toDoList/docker/celery.sh", "flower"]
    env_file:
      - .env-non-dev
    depends_on:
      - redis